name       : python-pypandoc
version    : 1.5
release    : 3
source     :
    - https://github.com/bebraw/pypandoc/archive/1.5.tar.gz : 949d0bba2a0932770932a0d72f90f15649dc26221caa2d72562081fb5adb0410
license    : MIT
component  : programming.python
summary    : Thin wrapper for pandoc
description: |
    Pypandoc provides a thin wrapper for pandoc, a universal document converter.
networking : yes
builddeps  :
    - pandoc-devel
    - pandoc-citeproc
    - python-wheel
    - texlive
    - texlive-fonts-extra
rundeps    :
    - pandoc
build      : |
    %python3_setup
check      : |
    %python3_test
install    : |
    %python3_install
